version: "3.7"

networks:
  net: {}

services:

  # https://hub.docker.com/_/php
  web:
    build:
      context: ./docker/apache-php8
      dockerfile: ./Dockerfile
      args:
        PHP_IMAGE_VERSION: "8.0"
        TIMEZONE: UTC
    ports:
      - 8020:80
    env_file:
      - ./docker.env
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      net:
        aliases: 
          - localhost

  # https://hub.docker.com/_/mysql/
  mysql:
    image: mysql:5.7
    ports:
      - 33306:3306
    volumes:
      - ./runtime/mysql:/var/lib/mysql
    command:
      - --sql-mode=
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --skip-character-set-client-handshake
    env_file:
      - docker.env
    networks:
      net: 
